### ISSUE TITLE
Can not get response client.horizon.transactions._post

### ISSUE THREAD

**Issue by dev-king21** [bloom-solutions/ruby-stellar-sdk#226]
I have created transactions in stellar laboratory and I got the XDR.

And I created the post request with this XDR.
But i got the error.
![image](https://user-images.githubusercontent.com/52515554/138907120-b53c2232-cd61-4a29-82ae-104cb4cd85c8.png)

My code:

   client = Stellar::Horizon::Client.default_testnet 
        envelope = params[:tx]
        begin
            client.horizon.transactions._post(tx: envelope)
        rescue Faraday::ClientError => e
            p 'error', e.response
        end

Regards,

**Comment by charlie-wasp** [comment]
@dev-king21 hi! Sorry for the late reply. As far as I can see from the log you attached, the error is `tx_too_late`. It means that your transaction has [time bounds](https://developers.stellar.org/docs/glossary/transactions/#time-bounds) set, and you submit it to the network later, than its `maxTime`. So I believe, SDK doesn't cause this issue. You can learn more about transaction error codes in this [doc](https://developers.stellar.org/api/errors/result-codes/transactions/). Hope, that helps

And btw, it's more convenient to have any log output as a text, rather than a screenshot, if that's possible

**Comment by charlie-wasp** [comment]
I'm closing it now due to inactivity. @dev-king21 feel free to reopen this issue, if you still experience troubles, or open a new one
